server:
  port: 8081
spring:
  application:
    name:
      microservice-employee

  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:employeeDb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  config:
    import: optional:configserver:instead
  eureka:
    instance:
      client:
        serviceUrl.defaultZone=http://localhost:8761/eureka/